### Test Root (cek server jalan)
GET https://login-app-three-eosin.vercel.app/
Content-Type: application/json

### Register user (dummy)
POST https://login-app-three-eosin.vercel.app/api/auth/register
Content-Type: application/json

{
  "email": "user@example.com",
  "password": "123456"
}

### Login berhasil (dummy admin)
POST https://login-app-three-eosin.vercel.app/api/auth/login
Content-Type: application/json

{
  "email": "admin@example.com",
  "password": "123456"
}

### Login gagal (password salah)
POST https://login-app-three-eosin.vercel.app/api/auth/login
Content-Type: application/json

{
  "email": "admin@example.com",
  "password": "wrongpass"
}
